#!/usr/bin/env python3

import os
import sys

sys.path.insert(0, os.path.abspath(os.path.join(__file__, "..", "..")))

from ncducolors.__main__ import main  # noqa: E402

if __name__ == "__main__":
    main()
